version: "3"

networks:
  inception:

volumes:
  v_wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/user42/data/v_wordpress
  v_database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/user42/data/v_database

services:
  nginx:
    container_name: nginx
    hostname: nginx
    build: ./requirements/nginx 
    ports:
      - "443:443"
      - "80:80"
    restart: "always"
    volumes:
      - "v_wordpress:/var/www:rw"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env

  wordpress:
    container_name: wordpress
    hostname: wordpresss
    build: ./requirements/wordpress
    restart: "always"
    volumes:
      - "v_wordpress:/var/www:rw"
    networks:
      - inception
    depends_on:
      - mariadb
    env_file: .env

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build: ./requirements/mariadb
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - "v_wordpress:/var/www:rw"
      - "v_database:/var/www:rw"
    networks:
      - inception
    env_file: .env
